server:
  port: 8088

logging:
  level:
     com.prism.springas.dao: debug

spring:
  application:
    name: springAS
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url:
      username: 
      password: 
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

configBasic:
  druidServer:
    allow: 
    deny:
    loginUsername: 
    loginPassword: 
    resetEnable: true

